-- MySQL Script generated by MySQL Workbench
-- Sat Apr  6 09:08:46 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_downisup
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_downisup
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_downisup` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish2_ci ;
USE `db_downisup` ;

-- -----------------------------------------------------
-- Table `db_downisup`.`socio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_downisup`.`socio` (
  `id_socio` INT NOT NULL AUTO_INCREMENT,
  `nombre_socio` VARCHAR(20) NOT NULL,
  `apellido_socio` VARCHAR(20) NOT NULL,
  `fecha_de_nacimiento_socio` DATE NOT NULL,
  `tipo_documento_socio` VARCHAR(8) NOT NULL,
  `num_documento_socio` INT NOT NULL,
  `estado_socio` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_socio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_downisup`.`familia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_downisup`.`familia` (
  `id_familia` INT NOT NULL AUTO_INCREMENT,
  `nombre_padre_familia` VARCHAR(20) NULL,
  `nombre_madre_familia` VARCHAR(20) NULL,
  `nombre_tutor_familia` VARCHAR(20) NULL,
  `telefono_familia` VARCHAR(11) NOT NULL,
  `celular_familia` VARCHAR(11) NOT NULL,
  `id_socio` INT NOT NULL,
  `estado_familia` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_familia`),
  INDEX `fk_familiaries_socio_idx` (`id_socio` ASC) ,
  CONSTRAINT `fk_familiaries_socio`
    FOREIGN KEY (`id_socio`)
    REFERENCES `db_downisup`.`socio` (`id_socio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_downisup`.`institucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_downisup`.`institucion` (
  `id_institucion` INT NOT NULL AUTO_INCREMENT,
  `nombre_institucion` VARCHAR(20) NOT NULL,
  `domicilio_institucion` VARCHAR(50) NOT NULL,
  `grado_institucion` VARCHAR(10) NULL,
  `id_socio` INT NOT NULL,
  `estado_institucion` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_institucion`),
  INDEX `fk_colegio_socio_idx` (`id_socio` ASC) ,
  CONSTRAINT `fk_colegio_socio`
    FOREIGN KEY (`id_socio`)
    REFERENCES `db_downisup`.`socio` (`id_socio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_downisup`.`domicilio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_downisup`.`domicilio` (
  `id_domicilio` INT NOT NULL AUTO_INCREMENT,
  `direccion_domicilio` VARCHAR(50) NOT NULL,
  `nombre_provincia_domicilio` VARCHAR(20) NULL,
  `nombre_localidad_domicilio` VARCHAR(50) NULL,
  `codigo_postal_domicilio` VARCHAR(7) NULL,
  `id_socio` INT NOT NULL,
  `estado_domicilio` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_domicilio`),
  INDEX `fk_localidad_socio_idx` (`id_socio` ASC) ,
  CONSTRAINT `fk_localidad_socio`
    FOREIGN KEY (`id_socio`)
    REFERENCES `db_downisup`.`socio` (`id_socio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = '		';


-- -----------------------------------------------------
-- Table `db_downisup`.`taller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_downisup`.`taller` (
  `id_taller` INT NOT NULL AUTO_INCREMENT,
  `nombre_taller` VARCHAR(20) NOT NULL,
  `descripcion_taller` VARCHAR(256) NOT NULL,
  `estado_taller` TINYINT(1) NOT NULL,
  `cuota_taller` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_taller`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_downisup`.`detalle_taller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_downisup`.`detalle_taller` (
  `id_detalle_taller` INT NOT NULL AUTO_INCREMENT,
  `cuota_detalle_taller_personal` DECIMAL(10,2) NULL,
  `estado_detalle_taller` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_detalle_taller`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_downisup`.`cat_organizacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_downisup`.`cat_organizacion` (
  `id_cat_organizacion` INT NOT NULL AUTO_INCREMENT,
  `nombre_cat_organizacion` VARCHAR(20) NOT NULL,
  `descripcion_cat_organizacion` VARCHAR(256) NULL,
  `estado_cat_organizacion` TINYINT NOT NULL,
  PRIMARY KEY (`id_cat_organizacion`))
ENGINE = InnoDB;

INSERT INTO `cat_organizacion` (`id_cat_organizacion`, `nombre_cat_organizacion`, `descripcion_cat_organizacion`, `estado_cat_organizacion`) VALUES
(1, 'Profesionales', 'Encargados del dictado de un determinado taller.', 1);

-- -----------------------------------------------------
-- Table `db_downisup`.`personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_downisup`.`personal` (
  `id_personal` INT NOT NULL AUTO_INCREMENT,
  `nombre_personal` VARCHAR(20) NOT NULL,
  `apellido_personal` VARCHAR(20) NOT NULL,
  `tipo_documento_personal` VARCHAR(8) NOT NULL,
  `num_documento_personal` VARCHAR(11) NOT NULL,
  `telefono_personal` VARCHAR(11) NOT NULL,
  `celular_personal` VARCHAR(11) NOT NULL,
  `correo_personal` VARCHAR(100) NOT NULL,
  `estado_personal` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`id_personal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_downisup`.`ingreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_downisup`.`ingreso` (
  `id_ingreso` INT NOT NULL AUTO_INCREMENT,
  `nombre_ingreso` VARCHAR(50) NOT NULL,
  `descripcion_ingreso` VARCHAR(256) NULL,
  `estado_ingreso` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_ingreso`))
ENGINE = InnoDB;

INSERT INTO `ingreso` (`id_ingreso`, `nombre_ingreso`, `descripcion_ingreso`, `estado_ingreso`) VALUES
(1, 'Cuota Organizacion', 'Cuota del socio correspondiente a la organizacion.', 1),
(2, 'Cuota Taller', 'Cuota de un determinado taller al que asista el socio.', 1),
(3, 'Ingreso Varios', '', 1);


-- -----------------------------------------------------
-- Table `db_downisup`.`egreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_downisup`.`egreso` (
  `id_egreso` INT NOT NULL AUTO_INCREMENT,
  `nombre_egreso` VARCHAR(50) NOT NULL,
  `descripcion_egreso` VARCHAR(256) NULL,
  `estado_egreso` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_egreso`))
ENGINE = InnoDB;

INSERT INTO `egreso` (`id_egreso`, `nombre_egreso`, `descripcion_egreso`, `estado_egreso`) VALUES
(1, 'Pago Personal', 'Pago del personal que trabaja en la organizacion.', 1),
(2, 'Pago Profesional', 'Pago de un profesional de acuerdo al taller que pertenece.', 1),
(3, 'Gastos Varios', '', 1);


-- -----------------------------------------------------
-- Table `db_downisup`.`detalle_ingreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_downisup`.`detalle_ingreso` (
  `id_detalle_ingreso` INT NOT NULL AUTO_INCREMENT,
  `id_ingreso` INT NOT NULL,
  `importe_detalle_ingreso` DECIMAL(10,2) NULL DEFAULT NULL,
  `fecha_detalle_ingreso` DATE NULL DEFAULT NULL,
  `descuento_detalle_ingreso` INT NULL DEFAULT NULL,
  `concepto_detalle_ingreso` VARCHAR(256) NULL DEFAULT NULL,
  `nombre_detalle_ingreso` VARCHAR(256) NULL DEFAULT NULL,
  `descripcion_detalle_ingreso` VARCHAR(246) NULL DEFAULT NULL,
  `estado_detalle_ingreso` VARCHAR(45) NULL,
  `mes_detalle_ingreso` VARCHAR(45) NULL,
  `año_detalle_ingreso` VARCHAR(45) NULL,
  PRIMARY KEY (`id_detalle_ingreso`),
  INDEX `fk_detalleingreso_ingreso_idx` (`id_ingreso` ASC) ,
  CONSTRAINT `fk_detalleingreso_ingreso`
    FOREIGN KEY (`id_ingreso`)
    REFERENCES `db_downisup`.`ingreso` (`id_ingreso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_downisup`.`detalle_egreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_downisup`.`detalle_egreso` (
  `id_detalle_egreso` INT NOT NULL AUTO_INCREMENT,
  `id_egreso` INT NOT NULL,
  `importe_detalle_egreso` DECIMAL(10,2) NOT NULL,
  `fecha_detalle_egreso` DATE NOT NULL,
  `descripcion_detalle_egreso` VARCHAR(256) NULL,
  `mes_detalle_egreso` INT NULL,
  `año_detalle_egreso` INT NULL,
  `estado_detalle_egreso` VARCHAR(45) NULL,
  PRIMARY KEY (`id_detalle_egreso`),
  INDEX `fk_detalleegreso_egreso_idx` (`id_egreso` ASC) ,
  CONSTRAINT `fk_detalleegreso_egreso`
    FOREIGN KEY (`id_egreso`)
    REFERENCES `db_downisup`.`egreso` (`id_egreso`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_downisup`.`administracion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_downisup`.`administracion` (
  `id_administracion` INT NOT NULL AUTO_INCREMENT,
  `cuota_fija_administracion` DECIMAL(10,2) NOT NULL,
  `fecha_cuota_fija_inicio_administracion` DATE NOT NULL,
  `fecha_cuota_fija_fin_administracion` DATE NULL,
  PRIMARY KEY (`id_administracion`),
  UNIQUE INDEX `id_administracion_UNIQUE` (`id_administracion` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_downisup`.`descuento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_downisup`.`descuento` (
  `id_descuento` INT NOT NULL AUTO_INCREMENT,
  `valor_descuento` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_descuento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_downisup`.`socio_has_descuento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_downisup`.`socio_has_descuento` (
  `socio_id_socio` INT NOT NULL,
  `descuento_id_descuento` INT NOT NULL,
  `fecha_inicio_socio_has_descuento` DATE NOT NULL,
  `fecha_fin_socio_has_descuento` DATE NOT NULL,
  INDEX `fk_socio_has_descuento_descuento1_idx` (`descuento_id_descuento` ASC) ,
  INDEX `fk_socio_has_descuento_socio1_idx` (`socio_id_socio` ASC) ,
  PRIMARY KEY (`socio_id_socio`, `descuento_id_descuento`),
  CONSTRAINT `fk_socio_has_descuento_socio1`
    FOREIGN KEY (`socio_id_socio`)
    REFERENCES `db_downisup`.`socio` (`id_socio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_socio_has_descuento_descuento1`
    FOREIGN KEY (`descuento_id_descuento`)
    REFERENCES `db_downisup`.`descuento` (`id_descuento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_downisup`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_downisup`.`users` (
  `name` VARCHAR(32) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(191) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `remember_token` VARCHAR(100) NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`));

INSERT INTO `users` (`name`, `email`, `password`, `created_at`, `id`, `remember_token`, `updated_at`) VALUES
('admin', 'admin@admin.com', '$2y$10$d0QXFAXouhGCUE1DEaL5u.pa66MdzrI/z0R3gtdxWaC..tNM5cSNu', '2019-03-31 22:54:36', 2, NULL, '2019-03-31 22:54:36');


-- -----------------------------------------------------
-- Table `db_downisup`.`detalle_taller_has_taller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_downisup`.`detalle_taller_has_taller` (
  `detalle_taller_id_detalle_taller` INT NOT NULL,
  `taller_id_taller` INT NOT NULL,
  `personal_id_personal` INT NOT NULL,
  PRIMARY KEY (`detalle_taller_id_detalle_taller`, `taller_id_taller`),
  INDEX `fk_detalle_taller_has_taller_taller1_idx` (`taller_id_taller` ASC) ,
  INDEX `fk_detalle_taller_has_taller_detalle_taller1_idx` (`detalle_taller_id_detalle_taller` ASC) ,
  CONSTRAINT `fk_detalle_taller_has_taller_detalle_taller1`
    FOREIGN KEY (`detalle_taller_id_detalle_taller`)
    REFERENCES `db_downisup`.`detalle_taller` (`id_detalle_taller`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_taller_has_taller_taller1`
    FOREIGN KEY (`taller_id_taller`)
    REFERENCES `db_downisup`.`taller` (`id_taller`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_downisup`.`personal_has_cat_organizacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_downisup`.`personal_has_cat_organizacion` (
  `personal_id_personal` INT NOT NULL,
  `cat_organizacion_id_cat_organizacion` INT NOT NULL,
  PRIMARY KEY (`personal_id_personal`, `cat_organizacion_id_cat_organizacion`),
  INDEX `fk_personal_has_cat_organizacion_cat_organizacion1_idx` (`cat_organizacion_id_cat_organizacion` ASC) ,
  INDEX `fk_personal_has_cat_organizacion_personal1_idx` (`personal_id_personal` ASC) ,
  CONSTRAINT `fk_personal_has_cat_organizacion_personal1`
    FOREIGN KEY (`personal_id_personal`)
    REFERENCES `db_downisup`.`personal` (`id_personal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_personal_has_cat_organizacion_cat_organizacion1`
    FOREIGN KEY (`cat_organizacion_id_cat_organizacion`)
    REFERENCES `db_downisup`.`cat_organizacion` (`id_cat_organizacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_downisup`.`taller_has_personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_downisup`.`taller_has_personal` (
  `id_taller_has_personal` INT NOT NULL AUTO_INCREMENT,
  `taller_id_taller` INT NOT NULL,
  `personal_id_personal` INT NOT NULL,
  `importe_taller_personal` DECIMAL(10,2) NULL,
  `estado_taller_personal` VARCHAR(45) NULL,
  INDEX `fk_taller_has_personal_personal1_idx` (`personal_id_personal` ASC) ,
  INDEX `fk_taller_has_personal_taller1_idx` (`taller_id_taller` ASC) ,
  PRIMARY KEY (`id_taller_has_personal`),
  CONSTRAINT `fk_taller_has_personal_taller1`
    FOREIGN KEY (`taller_id_taller`)
    REFERENCES `db_downisup`.`taller` (`id_taller`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_taller_has_personal_personal1`
    FOREIGN KEY (`personal_id_personal`)
    REFERENCES `db_downisup`.`personal` (`id_personal`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_downisup`.`detalle_egreso_has_personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_downisup`.`detalle_egreso_has_personal` (
  `detalle_egreso_id_detalle_egreso` INT NOT NULL,
  `personal_id_personal` INT NOT NULL,
  PRIMARY KEY (`detalle_egreso_id_detalle_egreso`, `personal_id_personal`),
  INDEX `fk_detalle_egreso_has_personal_personal1_idx` (`personal_id_personal` ASC) ,
  INDEX `fk_detalle_egreso_has_personal_detalle_egreso1_idx` (`detalle_egreso_id_detalle_egreso` ASC) ,
  CONSTRAINT `fk_detalle_egreso_has_personal_detalle_egreso1`
    FOREIGN KEY (`detalle_egreso_id_detalle_egreso`)
    REFERENCES `db_downisup`.`detalle_egreso` (`id_detalle_egreso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_egreso_has_personal_personal1`
    FOREIGN KEY (`personal_id_personal`)
    REFERENCES `db_downisup`.`personal` (`id_personal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_downisup`.`detalle_personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_downisup`.`detalle_personal` (
  `id_detalle_personal` INT NOT NULL AUTO_INCREMENT,
  `cuota_detalle_personal` DECIMAL(10,2) NULL,
  `mes_detalle_personal` INT NULL,
  `año_detalle_personal` INT NULL,
  PRIMARY KEY (`id_detalle_personal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_downisup`.`personal_has_detalle_personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_downisup`.`personal_has_detalle_personal` (
  `personal_id_personal` INT NOT NULL,
  `detalle_personal_id_detalle_personal` INT NOT NULL,
  `cat_organizacion_id_cat_organizacion` INT NOT NULL,
  PRIMARY KEY (`personal_id_personal`, `detalle_personal_id_detalle_personal`),
  INDEX `fk_personal_has_detalle_personal_detalle_personal1_idx` (`detalle_personal_id_detalle_personal` ASC) ,
  INDEX `fk_personal_has_detalle_personal_personal1_idx` (`personal_id_personal` ASC) ,
  CONSTRAINT `fk_personal_has_detalle_personal_personal1`
    FOREIGN KEY (`personal_id_personal`)
    REFERENCES `db_downisup`.`personal` (`id_personal`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_personal_has_detalle_personal_detalle_personal1`
    FOREIGN KEY (`detalle_personal_id_detalle_personal`)
    REFERENCES `db_downisup`.`detalle_personal` (`id_detalle_personal`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_downisup`.`socio_has_taller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_downisup`.`socio_has_taller` (
  `id_socio_has_taller` INT NOT NULL AUTO_INCREMENT,
  `socio_id_socio` INT NOT NULL,
  `taller_id_taller` INT NOT NULL,
  PRIMARY KEY (`id_socio_has_taller`),
  INDEX `fk_socio_has_taller_taller1_idx` (`taller_id_taller` ASC) ,
  INDEX `fk_socio_has_taller_socio1_idx` (`socio_id_socio` ASC) ,
  CONSTRAINT `fk_socio_has_taller_socio1`
    FOREIGN KEY (`socio_id_socio`)
    REFERENCES `db_downisup`.`socio` (`id_socio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_socio_has_taller_taller1`
    FOREIGN KEY (`taller_id_taller`)
    REFERENCES `db_downisup`.`taller` (`id_taller`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_downisup`.`socio_has_detalle_ingreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_downisup`.`socio_has_detalle_ingreso` (
  `socio_id_socio` INT NOT NULL,
  `detalle_ingreso_id_detalle_ingreso` INT NOT NULL,
  PRIMARY KEY (`socio_id_socio`, `detalle_ingreso_id_detalle_ingreso`),
  INDEX `fk_socio_has_detalle_ingreso_detalle_ingreso1_idx` (`detalle_ingreso_id_detalle_ingreso` ASC) ,
  INDEX `fk_socio_has_detalle_ingreso_socio1_idx` (`socio_id_socio` ASC) ,
  CONSTRAINT `fk_socio_has_detalle_ingreso_socio1`
    FOREIGN KEY (`socio_id_socio`)
    REFERENCES `db_downisup`.`socio` (`id_socio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_socio_has_detalle_ingreso_detalle_ingreso1`
    FOREIGN KEY (`detalle_ingreso_id_detalle_ingreso`)
    REFERENCES `db_downisup`.`detalle_ingreso` (`id_detalle_ingreso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_downisup`.`socio_has_taller_has_detalle_ingreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_downisup`.`socio_has_taller_has_detalle_ingreso` (
  `socio_has_taller_id_socio_has_taller` INT NOT NULL,
  `detalle_ingreso_id_detalle_ingreso` INT NOT NULL,
  PRIMARY KEY (`socio_has_taller_id_socio_has_taller`, `detalle_ingreso_id_detalle_ingreso`),
  INDEX `fk_socio_has_taller_has_detalle_ingreso_detalle_ingreso1_idx` (`detalle_ingreso_id_detalle_ingreso` ASC) ,
  INDEX `fk_socio_has_taller_has_detalle_ingreso_socio_has_taller1_idx` (`socio_has_taller_id_socio_has_taller` ASC) ,
  CONSTRAINT `fk_socio_has_taller_has_detalle_ingreso_socio_has_taller1`
    FOREIGN KEY (`socio_has_taller_id_socio_has_taller`)
    REFERENCES `db_downisup`.`socio_has_taller` (`id_socio_has_taller`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_socio_has_taller_has_detalle_ingreso_detalle_ingreso1`
    FOREIGN KEY (`detalle_ingreso_id_detalle_ingreso`)
    REFERENCES `db_downisup`.`detalle_ingreso` (`id_detalle_ingreso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_downisup`.`taller_has_personal_has_detalle_egreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_downisup`.`taller_has_personal_has_detalle_egreso` (
  `taller_has_personal_id_taller_has_personal` INT NOT NULL,
  `detalle_egreso_id_detalle_egreso` INT NOT NULL,
  PRIMARY KEY (`taller_has_personal_id_taller_has_personal`, `detalle_egreso_id_detalle_egreso`),
  INDEX `fk_taller_has_personal_has_detalle_egreso_detalle_egreso1_idx` (`detalle_egreso_id_detalle_egreso` ASC) ,
  INDEX `fk_taller_has_personal_has_detalle_egreso_taller_has_person_idx` (`taller_has_personal_id_taller_has_personal` ASC) ,
  CONSTRAINT `fk_taller_has_personal_has_detalle_egreso_taller_has_personal1`
    FOREIGN KEY (`taller_has_personal_id_taller_has_personal`)
    REFERENCES `db_downisup`.`taller_has_personal` (`id_taller_has_personal`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_taller_has_personal_has_detalle_egreso_detalle_egreso1`
    FOREIGN KEY (`detalle_egreso_id_detalle_egreso`)
    REFERENCES `db_downisup`.`detalle_egreso` (`id_detalle_egreso`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
